BRANDS = [
    {
        "id": "axxiom",
        "name": "Axxiom Elevator",
        "wp_url": "https://axxiomelevator.com",
        "markets": ["National"],
        "is_corporate": True,
        "phone": None,
        "author_name": "Axxiom Elevator",
        "logo_url": "https://axxiomelevator.com/wp-content/uploads/2023/10/Axxiom_Color_NoTag.png",
    },
    {
        "id": "ameritex",
        "name": "AmeriTex Elevator",
        "wp_url": "https://ameritexelevator.com",
        "markets": ["Houston TX", "Dallas TX", "Austin TX", "San Antonio TX", "Los Angeles CA", "San Diego CA"],
        "is_corporate": False,
        "phone": "866-679-4313",
        "author_name": "Trey Rast",
    },
    {
        "id": "arizona_es",
        "name": "Arizona Elevator Solutions",
        "wp_url": "https://azelevatorsolutions.com",
        "markets": ["Phoenix AZ", "Tucson AZ", "Scottsdale AZ", "Mesa AZ"],
        "is_corporate": False,
        "phone": "480-319-7157",
        "author_name": "Axxiom Elevator",
    },
    {
        "id": "liftech",
        "name": "Liftech Elevator",
        "wp_url": "https://liftechelevator.com",
        "markets": ["Signal Hill CA", "Long Beach CA", "Los Angeles CA", "Orange County CA"],
        "is_corporate": False,
        "phone": "562-609-3478",
        "author_name": "Axxiom Elevator",
    },
    {
        "id": "motion",
        "name": "Motion Elevator Services",
        "wp_url": "https://motionelevator.com",
        "markets": ["Miami FL", "Fort Lauderdale FL", "West Palm Beach FL", "Tampa FL"],
        "is_corporate": False,
        "phone": "954-833-5503",
        "author_name": "Axxiom Elevator",
    },
    {
        "id": "quality",
        "name": "Quality Elevator Company",
        "wp_url": "https://qualityelevator.com",
        "markets": ["Baltimore MD", "Washington DC", "Philadelphia PA", "Richmond VA"],
        "is_corporate": False,
        "phone": "301-307-5363",
        "author_name": "Eric Amundson",
    },
    {
        "id": "evolution",
        "name": "Evolution Elevator & Escalator Corp.",
        "wp_url": "https://evolutionelevator.com",
        "markets": ["Staten Island NY", "Brooklyn NY", "Fort Lauderdale FL"],
        "is_corporate": False,
        "author_name": "Axxiom Elevator",
    },
    {
        "id": "ironhawk",
        "name": "IronHawk Elevator",
        "wp_url": "https://ironhawkelevator.com",
        "markets": ["Phoenix AZ", "Tucson AZ", "Albuquerque NM"],
        "is_corporate": False,
        "author_name": "Axxiom Elevator",
    },
]

CONTENT_QUEUE_SEED = [
    {"brand_id": "axxiom", "content_type": "faq_hub", "title": "Complete Guide to Elevator Maintenance", "target_query": "how often should elevators be inspected", "priority": 1, "scheduled_for": "2026-06-23"},
    {"brand_id": "ameritex", "content_type": "local_page", "title": "Elevator Service in Houston TX", "target_query": "elevator service Houston TX", "priority": 1, "scheduled_for": "2026-06-23"},
    {"brand_id": "ameritex", "content_type": "local_page", "title": "Elevator Service in Dallas TX", "target_query": "elevator service Dallas TX", "priority": 1, "scheduled_for": "2026-06-23"},
    {"brand_id": "arizona_es", "content_type": "local_page", "title": "Elevator Service in Phoenix AZ", "target_query": "elevator service Phoenix AZ", "priority": 1, "scheduled_for": "2026-06-23"},
    {"brand_id": "axxiom", "content_type": "data_stats", "title": "Elevator Inspection Requirements by State", "target_query": "elevator inspection requirements by state", "priority": 1, "scheduled_for": "2026-06-30"},
    {"brand_id": "axxiom", "content_type": "faq_hub", "title": "Emergency Elevator Repair FAQ", "target_query": "elevator out of service what to do", "priority": 1, "scheduled_for": "2026-06-30"},
    {"brand_id": "ameritex", "content_type": "faq_hub", "title": "Emergency Elevator Repair FAQ", "target_query": "elevator out of service what to do", "priority": 1, "scheduled_for": "2026-06-30"},
    {"brand_id": "arizona_es", "content_type": "faq_hub", "title": "Emergency Elevator Repair FAQ", "target_query": "elevator out of service what to do", "priority": 1, "scheduled_for": "2026-06-30"},
    {"brand_id": "axxiom", "content_type": "vertical_page", "title": "Healthcare Elevator Maintenance: Complete Guide", "target_query": "hospital elevator requirements and maintenance", "priority": 3, "scheduled_for": "2026-07-07"},
    {"brand_id": "axxiom", "content_type": "vertical_page", "title": "Office Building Elevator Service", "target_query": "commercial building elevator service contract", "priority": 3, "scheduled_for": "2026-07-07"},
    {"brand_id": "axxiom", "content_type": "comparison", "title": "Elevator Modernization vs. Full Replacement", "target_query": "elevator modernization vs replacement cost", "priority": 3, "scheduled_for": "2026-07-14"},
    {"brand_id": "axxiom", "content_type": "comparison", "title": "OEM vs. Independent Elevator Service", "target_query": "elevator service company vs OEM manufacturer", "priority": 3, "scheduled_for": "2026-07-14"},
    {"brand_id": "axxiom", "content_type": "vertical_page", "title": "Hotel Elevator Maintenance Best Practices", "target_query": "hotel elevator maintenance best practices", "priority": 3, "scheduled_for": "2026-07-21"},
    {"brand_id": "axxiom", "content_type": "vertical_page", "title": "Multifamily Elevator Maintenance Requirements", "target_query": "apartment building elevator maintenance requirements", "priority": 3, "scheduled_for": "2026-07-21"},
    {"brand_id": "axxiom", "content_type": "data_stats", "title": "Elevator Industry Statistics 2025-2026", "target_query": "elevator industry statistics 2025", "priority": 5, "scheduled_for": "2026-07-28"},
    {"brand_id": "quality", "content_type": "local_page", "title": "Elevator Service in Baltimore MD", "target_query": "elevator service Baltimore MD", "priority": 1, "scheduled_for": "2026-06-23"},
    {"brand_id": "liftech", "content_type": "local_page", "title": "Elevator Service in Los Angeles CA", "target_query": "elevator service Los Angeles CA", "priority": 3, "scheduled_for": "2026-07-07"},
    {"brand_id": "motion", "content_type": "local_page", "title": "Elevator Service in Miami FL", "target_query": "elevator service Miami FL", "priority": 3, "scheduled_for": "2026-07-07"},
]
